# Generated by Django 3.2.5 on 2022-01-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_auto_20210801_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='prereq_group',
            field=models.CharField(help_text='Comma-separated slugs of puzzles, any of which must be solved to unlock this one', max_length=1024),
        ),
    ]
